# Generated by Django 5.0.6 on 2024-05-27 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_alter_tweet_options_tweet_likes_tweet_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="finished_at",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
